# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js Continuous Integration

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  pull_request:
    env: 
      DB_CONNECTION = ${{ secrets.DB_CONNECTION }}
      TOKEN_SECRET = ${{ secrets.TOKEN_SECRET }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12.3
      - run: npm install
      - run: npm test
      - run: npm run build --if-present